# This is a comment in a makefile

# Variable Definitions
CPP          = g++
CPPFLAGS     = -g -Wall -o main -std=c++11

all:		*.cpp *.h								# File dependencies: create new file if any of these have changed
		$(CPP) $(CPPFLAGS) *.cpp					# Compile command

